import type { IconType } from 'react-icons';
import {
  SiDotnet,
  SiJavascript,
  SiTypescript,
  SiPostgresql,
  SiMysql,
  SiReact,
  SiRabbitmq,
  SiDocker,
  SiKubernetes,
  SiGithubactions,
  SiGit,
  SiJsonwebtokens,
  SiSharp,
} from 'react-icons/si';
import { VscAzure } from 'react-icons/vsc';
import {
  FiTerminal,
  FiCode,
  FiLayers,
  FiGitBranch,
  FiServer,
  FiDatabase,
  FiCloud,
  FiCheckCircle,
  FiRepeat,
  FiZap,
  FiBox,
} from 'react-icons/fi';

const iconMap: Record<string, IconType> = {
  'C#': SiSharp,
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  SQL: FiDatabase,
  PowerShell: FiTerminal,
  YAML: FiCode,
  '.NET 10': SiDotnet,
  'ASP.NET Core': SiDotnet,
  'Entity Framework Core': FiDatabase,
  LINQ: SiSharp,
  React: SiReact,
  Razor: FiCode,
  'ASP.NET MVC': SiDotnet,
  'RESTful APIs': FiServer,
  Microservices: FiBox,
  'Event-Driven Architecture': FiZap,
  'SOLID Principles': FiLayers,
  'Design Patterns': FiLayers,
  'Azure PaaS': VscAzure,
  'Azure API Management': VscAzure,
  'Azure Kubernetes Service': SiKubernetes,
  'Azure DevOps': VscAzure,
  'GitHub Actions': SiGithubactions,
  Docker: SiDocker,
  Kubernetes: SiKubernetes,
  'CI/CD': FiGitBranch,
  'Cloud Migration': FiCloud,
  'Application Modernization': FiRepeat,
  'Cloud-Native Development': FiCloud,
  RabbitMQ: SiRabbitmq,
  'SQL Server': FiDatabase,
  PostgreSQL: SiPostgresql,
  Dapper: SiJsonwebtokens,
  xUnit: FiCheckCircle,
  TDD: FiCheckCircle,
  BDD: FiCheckCircle,
  Refactoring: FiRepeat,
  'Software Testing & QA': FiCheckCircle,
  WebAssembly: FiBox,
  Roslyn: SiSharp,
  HTML5: FiCode,
  CSS3: FiCode,
  Vite: FiZap,
  'GitHub Pages': SiGithubactions,
  Algorithms: FiLayers,
  'Data Structures': FiLayers,
  Git: SiGit,
  MySQL: SiMysql,
};

export function getTechIcon(name: string): IconType {
  return iconMap[name] ?? FiCode;
}

export const categoryAccents: Record<string, string> = {
  'Languages & Configuration': 'from-sky-500 to-blue-600',
  'Frameworks & Application Development': 'from-violet-500 to-fuchsia-600',
  'Cloud, Platform & DevOps': 'from-cyan-500 to-teal-600',
  'Messaging & Data': 'from-amber-500 to-orange-600',
  Quality: 'from-emerald-500 to-green-600',
};
